name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: 'x64'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install
    - name: mypy
      run: poetry run mypy --strict migrator
    - name: pylint
      run: poetry run pylint migrator
    - name: flake8
      run: poetry run flake8 migrator
    - name: test
      run: poetry run pytest --cov